import java.awt.Dimension;
import java.awt.FlowLayout;
import java.beans.XMLDecoder;
import java.beans.XMLEncoder;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JFrame;
import javax.swing.JLabel;

public class WynikOkno extends javax.swing.JFrame {
	private int czas;
	private int lbPlemion;
	private int idWyniku;
	private ArrayList<Wyniki> wynik;

	/**
	 * Creates new form WynikOkno
	 */
	public WynikOkno(int czas, int lbPlemion) {
		// jLabel5=new JLabel();
		// jLabel6=new JLabel();
		// jLabel5.setText(" "+czas);
		this.czas = czas;
		this.lbPlemion = lbPlemion;
		this.idWyniku = (((czas - lbPlemion) / 10) + 20);
		wynik = new ArrayList<>();
		// jLabel6.setText(" "+lbPlemion);
		initComponents();
		setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTextField1 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jTextField1.setText("Podaj imiê");
		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jLabel1.setText("Podaj Imie:");

		jLabel2.setText("Koniec gry!");

		jLabel3.setText("Czas gry:");

		jLabel4.setText("Liczba Pokonanych Plemion:");

		jLabel5.setText(" " + czas);

		jButton1.setText("OK");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel8.setText("" + lbPlemion);

		jLabel9.setText("Id wyniku:");

		jLabel10.setText(" " + idWyniku);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(56, 56,
																		56)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						90,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jTextField1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						128,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING,
																												false)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		jLabel3,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		108,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addGap(65,
																																		65,
																																		65)
																																.addComponent(
																																		jLabel5,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		64,
																																		javax.swing.GroupLayout.PREFERRED_SIZE))
																												.addGroup(
																														javax.swing.GroupLayout.Alignment.LEADING,
																														layout.createSequentialGroup()
																																.addComponent(
																																		jLabel9,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		59,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		Short.MAX_VALUE)
																																.addComponent(
																																		jLabel10,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		76,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jLabel7)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jLabel6))
																				.addComponent(
																						jLabel2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						224,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel4,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										165,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jLabel8))))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(166,
																		166,
																		166)
																.addComponent(
																		jButton1)))
								.addContainerGap(95, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(19, 19, 19)
								.addComponent(jLabel2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										14,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(jLabel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										14,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jTextField1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jLabel9,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														13,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jLabel10,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														15,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel3)
												.addComponent(
														jLabel5,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														14,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4)
												.addComponent(jLabel8))
								.addGap(18, 18, 18)
								.addComponent(jButton1)
								.addGap(9, 9, 9)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel6)
												.addComponent(jLabel7))
								.addContainerGap(88, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		JLabel label0, label1, label2, label3, label4, label5, label6;
		label0 = new JLabel();
		label1 = new JLabel();
		label2 = new JLabel();
		label3 = new JLabel();
		label4 = new JLabel();
		label5 = new JLabel();
		label6 = new JLabel();
		Wyniki w = new Wyniki();
		ArrayList<Wyniki> wynik2 = new ArrayList<>();
		w.setCzasRozgrywki(czas);
		w.setIdWyniku(idWyniku);
		w.setImie(jTextField1.getText());
		w.setLiczbaPokonanychPlemion(lbPlemion);
		String nazwaPliku = "C:\\Users\\hania20\\Documents\\NetBeansProjects\\Imperium\\src\\imperium\\serializacja.xml";
		File file = new File(nazwaPliku);
		if (file.exists()) {
		} else {
			return;
		}
		try {
			XMLDecoder xmld = new XMLDecoder(new BufferedInputStream(
					new FileInputStream(nazwaPliku)));
			wynik = (ArrayList<Wyniki>) xmld.readObject();
			xmld.close();
		} catch (Exception ex) {
			ex.printStackTrace();
		}
		wynik.add(w);
		Collections.sort(wynik);
		while (wynik.size() > 5) {
			wynik.remove(5);
		}
		try {
			XMLEncoder xmle = new XMLEncoder(new BufferedOutputStream(
					new FileOutputStream(nazwaPliku)));

			xmle.writeObject(wynik);

			xmle.close();
		} catch (Exception ex) {
			ex.printStackTrace();
		}
		if (file.exists()) {
		} else {
			return;
		}
		try {
			XMLDecoder xmld = new XMLDecoder(new BufferedInputStream(
					new FileInputStream(nazwaPliku)));

			wynik2 = (ArrayList<Wyniki>) xmld.readObject();
			xmld.close();
		} catch (Exception ex) {
			ex.printStackTrace();
		}
		this.setVisible(false);
		JFrame Wyswietlenie = new JFrame();
		Wyswietlenie.setSize(600, 400);
		Wyswietlenie.setLocation(300, 150);
		Wyswietlenie.setLayout(new FlowLayout(FlowLayout.LEFT));
		Wyswietlenie.setResizable(false);
		label0.setPreferredSize(new Dimension(600, 12));
		label1.setPreferredSize(new Dimension(600, 12));
		label2.setPreferredSize(new Dimension(600, 12));
		label3.setPreferredSize(new Dimension(600, 12));
		label4.setPreferredSize(new Dimension(600, 12));
		label5.setPreferredSize(new Dimension(600, 12));
		label6.setPreferredSize(new Dimension(600, 12));
		label0.setText("Najlepsze wyniki:");
		label6.setText("Imiê gracza:       Liczba pokonanych plemion:     Czas:");
		label1.setText(wynik2.get(0).getImie()
				+ "                                 "
				+ wynik2.get(0).getLiczbaPokonanychPlemion()
				+ "                                   "
				+ wynik2.get(0).getCzasRozgrywki());
		label2.setText(wynik2.get(1).getImie()
				+ "                                 "
				+ wynik2.get(1).getLiczbaPokonanychPlemion()
				+ "                                   "
				+ wynik2.get(1).getCzasRozgrywki());
		label3.setText(wynik2.get(2).getImie()
				+ "                                 "
				+ wynik2.get(2).getLiczbaPokonanychPlemion()
				+ "                                    "
				+ wynik2.get(2).getCzasRozgrywki());
		label4.setText(wynik2.get(3).getImie()
				+ "                                 "
				+ wynik2.get(3).getLiczbaPokonanychPlemion()
				+ "                                   "
				+ wynik2.get(3).getCzasRozgrywki());
		label5.setText(wynik2.get(4).getImie()
				+ "                                    "
				+ wynik2.get(4).getLiczbaPokonanychPlemion()
				+ "                                   "
				+ wynik2.get(4).getCzasRozgrywki());

		Wyswietlenie.getContentPane().add(label0);
		Wyswietlenie.getContentPane().add(label6);
		Wyswietlenie.getContentPane().add(label1);
		Wyswietlenie.getContentPane().add(label2);
		Wyswietlenie.getContentPane().add(label3);
		Wyswietlenie.getContentPane().add(label4);
		Wyswietlenie.getContentPane().add(label5);
		Wyswietlenie.setVisible(true);

	}

	/**
	 * @param args
	 *            the command line arguments
	 */

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField jTextField1;
}
